require "rake"
require "rake/clean"
require "rake/gempackagetask"
require "rake/rdoctask"
require "fileutils"

def __DIR__
  File.dirname(__FILE__)
end

include FileUtils

NAME = "merb"
VERSION = "0.9.0"

desc "Packages up Merb."
task :default => :package

spec = Gem::Specification.new do |s|
  s.name         = NAME
  s.version      = VERSION
  s.platform     = Gem::Platform::RUBY
  s.author       = "Ezra Zygmuntowicz"
  s.email        = "ez@engineyard.com"
  s.homepage     = "http://merb.devjavu.com"
  s.summary      = "Merb. Pocket rocket web framework."
  s.description  = s.summary
  s.files        = %w( LICENSE README )
  s.has_rdoc         = true
  s.extra_rdoc_files = %w( README LICENSE )

  # Dependencies
  s.add_dependency "merb-core #{VERSION}"
  s.add_dependency "merb-gen #{VERSION}"
end

Rake::GemPackageTask.new(spec) do |package|
  package.gem_spec = spec
end

task :release => :package do
  if ENV["RELEASE"]
    sh %{rubyforge add_release merb merb "#{ENV["RELEASE"]}" pkg/#{NAME}-#{Merb::VERSION}.gem}
  else
    puts "Usage: rake release RELEASE='Clever tag line goes here'"
  end
end