#!/usr/bin/env ruby
require 'fileutils'

pids=[]

port_or_star = ARGV[0] || '*'

Dir[File.dirname(__FILE__)+"/../log/merb.#{port_or_star}.pid"].each do |f|
  pid = IO.read(f).chomp.to_i
  puts "killing PID: #{pid}"
  Process.kill(9, pid)
  FileUtils.rm f
end
